
server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
game:
  figureUser: O
    #spring.jpa.database-platform: org.hibernate.dialect.H2Dialect